version: "3"

services:
  devenv:
    container_name: devenv
    build:
      context: .
    volumes:
      - ~/.zsh.d/.zsh-history:/home/yunabe/.zsh.d/.zsh-history
    ports:
      # sshd
      - "8156:22"
      - "8080:8080"
      - "8888:8888"
