---
- hosts: all
  become: yes
  # Overwrite them with --extra-vars='{"user": "yunabe"}'
  # http://docs.ansible.com/ansible/playbooks_variables.html
  #
  # Notes:
  # 1. The default `ubuntu` user are groups like `sudo` to have some previledges.
  #    If you want to use another user name, please be careful about it.
  # 2. `developer` group is created to demostrate how to add a group with ansible.
  #     The group is not used for any real task.
  vars:
    user: ubuntu
    group: developer

  tasks:
  - name: Ensure apt packages are installed
    apt:
      name: "{{ item }}"
      force: yes
      update_cache: yes
      cache_valid_time: 3600
    with_items:
      # apptitude is required to execute apt: upgrade later.
      # https://github.com/ansible/ansible/issues/16884#issuecomment-278138707
      - aptitude
      - cargo
      - clang
      - emacs
      - gcc
      - git
      - golang
      - npm
      - openjdk-8-jdk
      - python-pip
      - rustc
      - screen
      - unzip
      - zip
      - zsh

  - name: Update all packages to the latest version
    apt: update_cache=yes cache_valid_time=3600 upgrade=safe

  - name: autoclean unused apt packages.
    apt: update_cache=yes cache_valid_time=3600 autoremove=true

  # Run this before other pip modules.
  # pip installed with apt-get is not up-to-date.
  - name: Ensure pip is up-to-date.
    pip: name=pip state=latest

  # --no-cche-dir is required to avoid MemoryError.
  # pip skips packages which were already installed even with --no-cache-dir option.
  - name: Ensure popular ML python libraries are installed.
    pip:
      state: latest
      extra_args: --no-cache-dir
      name:
      - jupyter
      - matplotlib
      - numpy
      - pandas
      - scikit-learn
      - scipy
      - tensorflow
      - keras

  # Install the latest version of docker on ubuntu.
  # https://docs.docker.com/engine/installation/linux/ubuntu/
  - name: Install Docker GPG key
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      id: 0EBFCD88
      
  - name: Register docker apt-repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
      update_cache: yes

  - name: Ensure docker-ce is installed
    apt:
      name: docker-ce
      force: yes
      update_cache: yes
      cache_valid_time: 3600

  # Apply a patch to disable sshd password authentication.
  - name: Apply patches to modify configurations
    patch:
      src: root_config.patch
      basedir: /

  # Set up users and groups.
  - name: Ensure group:{{ group }} exists
    group: name={{ group }}

  # http://docs.ansible.com/ansible/user_module.html
  - name: Ensure user:{{ user }} exists
    user:
      # Why is "" necessary?
      name: "{{ user }}"
      # append is necessary because ubuntu needs to be in
      # some default groups like sudo.
      append: yes
      # Remove default public password in Vagrant. Double-quotes around * are necessary.
      password: "*"
      shell: /bin/zsh
      groups:
      - "{{ group }}"
      - docker

  - name: Create .ssh directory
    file:
      path: /home/{{ user }}/.ssh
      state: directory
      mode: 0700
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy a ssh private key for devenv
    copy:
      src: ~/.ssh/devenv_id_rsa
      dest: /home/{{ user }}/.ssh/id_rsa
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0600

  - name: Copy a ssh public key for devenv
    copy:
      src: ~/.ssh/devenv_id_rsa.pub
      dest: /home/{{ user }}/.ssh/id_rsa.pub
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - name: Clone config git repository
    become_user: "{{ user }}"
    git:
      repo: git@github.com:yunabe/linux-user-config.git
      dest: /home/{{ user }}/config
      accept_hostkey: yes

  # Ansible version of config/setup.sh.
  # Group these file modules as a role.
  - name: Link .emacs file
    file:
      path: /home/{{ user }}/.emacs
      src: /home/{{ user }}/config/_emacs
      state: link
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Link .zshrc file
    file:
      path: /home/{{ user }}/.zsh.d
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Make .zsh.d directory
    file:
      path: /home/{{ user }}/.zshrc
      src: /home/{{ user }}/config/_zshrc
      state: link
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Link .screenrc file
    file:
      path: /home/{{ user }}/.screenrc
      src: /home/{{ user }}/config/_screenrc
      state: link
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Link .gitconfig file
    file:
      path: /home/{{ user }}/.gitconfig
      src: /home/{{ user }}/config/_gitconfig
      state: link
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Clone codelab git repository
    become_user: "{{ user }}"
    git:
      repo: git@github.com:yunabe/codelab.git
      dest: /home/{{ user }}/src/codelab
      accept_hostkey: yes

  - name: Clone golang-codelab git repository
    become_user: "{{ user }}"
    git:
      repo: git@github.com:yunabe/golang-codelab.git
      dest: /home/{{ user }}/local/gocode/src/github.com/yunabe/golang-codelab
      accept_hostkey: yes

  - name: Clone easycsv git repository
    become_user: "{{ user }}"
    git:
      repo: git@github.com:yunabe/easycsv.git
      dest: /home/{{ user }}/local/gocode/src/github.com/yunabe/easycsv
      accept_hostkey: yes

  - name: Clone pysh git repository
    become_user: "{{ user }}"
    git:
      repo: git@github.com:yunabe/pysh.git
      dest: /home/{{ user }}/src/pysh
      accept_hostkey: yes

  - name: Clone jekylldoc git repository
    become_user: "{{ user }}"
    git:
      repo: git@bitbucket.org:yunabe/sphinx-doc.git
      dest: /home/{{ user }}/src/jekylldoc
      accept_hostkey: yes

  - name: Clone plain git repository
    become_user: "{{ user }}"
    git:
      repo: git@bitbucket.org:yunabe/plain.git
      dest: /home/{{ user }}/src/plain
      accept_hostkey: yes
